const defaultFog = {
  fogEnabled: 0.35,
  fogNear: 0,
  fogFar: 50,
  fogAmount: 0.8,
  fogColorSrgb: [0.34, 0.37, 0.47],
};

function uniforms(overrides) {
  return {
    ...defaultFog,
    gradeTint: [1, 1, 1],
    gradeOffset: [0, 0, 0],
    saturation: 1,
    contrast: 1,
    greenSuppress: 1,
    gradeMix: 0,
    chromaticStrength: 0,
    chromaticEdgeFalloff: 3,
    vignetteIntensity: 0,
    vignetteSmoothness: 0.65,
    grainIntensity: 0,
    ...overrides,
  };
}

export const LOOK_PRESETS = {
  neutral: {
    id: "neutral",
    label: "Neutral",
    bloom: { strength: 3, radius: 0.5 },
    bloomWide: { strength: 1.25, radius: 1 },
    lensflare: { strength: 0, threshold: 0.6, ghostSpacing: 0.25, ghostAttenuation: 25 },
    uniforms: uniforms({
      fogColorSrgb: [0.36, 0.38, 0.42],
    }),
  },
  neonNoir: {
    id: "neonNoir",
    label: "Neon Noir",
    bloom: { strength: 0.62, radius: 0.5 },
    bloomWide: { strength: 1.45, radius: 0.72 },
    lensflare: { strength: 0.35, threshold: 0.9, ghostSpacing: 0.22, ghostAttenuation: 50 },
    uniforms: uniforms({
      gradeTint: [1.02, 0.9, 1.06],
      gradeOffset: [0.004, -0.006, 0.008],
      saturation: 1.06,
      contrast: 1.1,
      greenSuppress: 0.72,
      gradeMix: 0.7,
      chromaticStrength: 0.8,
      chromaticEdgeFalloff: 3.5,
      vignetteIntensity: 0.8,
      vignetteSmoothness: 0.64,
      grainIntensity: 0.12,
    }),
  },
  magentaRain: {
    id: "magentaRain",
    label: "Magenta Rain",
    bloom: { strength: 5, radius: 0.72 },
    bloomWide: { strength: 2.6, radius: 1 },
    lensflare: { strength: 0.2, threshold: 0.45, ghostSpacing: 0.2, ghostAttenuation: 22 },
    uniforms: uniforms({
      fogColorSrgb: [0.4, 0.34, 0.44],
      gradeTint: [1.08, 0.9, 1.08],
      gradeOffset: [0.012, -0.015, 0.01],
      saturation: 1.28,
      contrast: 1.12,
      greenSuppress: 0.68,
      gradeMix: 0.9,
      chromaticStrength: 0.85,
      chromaticEdgeFalloff: 3.5,
      vignetteIntensity: 0.5,
      vignetteSmoothness: 0.55,
      grainIntensity: 0.3,
    }),
  },
  tealDusk: {
    id: "tealDusk",
    label: "Teal Dusk",
    bloom: { strength: 3.6, radius: 0.58 },
    bloomWide: { strength: 1.85, radius: 0.78 },
    lensflare: { strength: 0.55, threshold: 0.6, ghostSpacing: 0.24, ghostAttenuation: 30 },
    uniforms: uniforms({
      fogColorSrgb: [0.32, 0.38, 0.46],
      gradeTint: [0.94, 0.98, 1.06],
      gradeOffset: [-0.008, 0, 0.01],
      saturation: 1.06,
      contrast: 1.06,
      greenSuppress: 0.8,
      gradeMix: 0.72,
      chromaticStrength: 0.28,
      chromaticEdgeFalloff: 3,
      vignetteIntensity: 0.3,
      vignetteSmoothness: 0.68,
      grainIntensity: 0.14,
    }),
  },
  silentHill: {
    id: "silentHill",
    label: "Silent Hill",
    bloom: { strength: 1.41, radius: 1 },
    bloomWide: { strength: 0, radius: 0 },
    lensflare: { strength: 0, threshold: 0.6, ghostSpacing: 0.25, ghostAttenuation: 25 },
    uniforms: uniforms({
      fogEnabled: 1,
      fogNear: -20,
      fogFar: 30,
      fogAmount: 1,
      fogColorSrgb: [0.37, 0.38, 0.39],
      saturation: 0.42,
      contrast: 1.91,
      greenSuppress: 0,
      gradeMix: 0.24,
      chromaticStrength: 0.61,
      chromaticEdgeFalloff: 12,
      vignetteIntensity: 0.63,
      vignetteSmoothness: 0,
      grainIntensity: 0.48,
    }),
  },
  sinCity: {
    id: "sinCity",
    label: "Sin City",
    bloom: { strength: 2.9, radius: 0.59 },
    bloomWide: { strength: 0, radius: 0 },
    lensflare: { strength: 0, threshold: 0.6, ghostSpacing: 0.25, ghostAttenuation: 25 },
    uniforms: uniforms({
      fogEnabled: 1,
      fogNear: -13,
      fogFar: 53,
      fogAmount: 0.83,
      fogColorSrgb: [0.47, 0, 0.58],
      saturation: 0,
      contrast: 2,
      greenSuppress: 1,
      gradeMix: 1,
      chromaticStrength: 0.79,
      chromaticEdgeFalloff: 4.17,
      vignetteIntensity: 0.77,
      vignetteSmoothness: 0.24,
      grainIntensity: 0,
    }),
  },
};

export const LOOK_PRESET_ORDER = [
  "neutral",
  "neonNoir",
  "magentaRain",
  "tealDusk",
  "silentHill",
  "sinCity",
];

export const DEFAULT_LOOK_ID = "neonNoir";
