export const ASSETS = {
  city: "/models/cyberpunk_compressed.glb",
  collider: "/models/colider.glb",
  billboards: "/models/billboards.glb",
  car: "/models/quadra.glb",
  character: "/models/ual.glb",
  plane: "/models/plane.glb",
  puddleAlbedo: "/textures/wet-puddles-albedo.jpg",
  puddleRoughness: "/textures/wet-puddles-roughness.jpg",
  puddleNormal: "/textures/wet-puddles-normal.jpg",
  splash: "/textures/water-splash.webp",
  noise: "/custom_noise.webp",
  perlin: "/custom_perlin.webp",
  videos: [
    "/video/imagine-art-feed-item.mp4",
    "/video/imagine-art-feed-item-2.mp4",
    "/video/imagine-art-feed-item-3.mp4",
    "/video/imagine-art-feed-item-4.mp4",
    "/video/imagine-art-feed-item-5.mp4",
    "/video/imagine-art-feed-item-6.mp4",
  ],
  audio: {
    rain: "/light-rain.mp3",
    night: "/night-ambience.mp3",
    thunder: "/thunderstorm.mp3",
    engine: "/engine.mp3",
    plane: "/freesound_community-plasma-engine-fx-33559.mp3",
    footsteps: [
      "/wet_footstep-step-01.mp3",
      "/wet_footstep-step-02.mp3",
      "/wet_footstep-step-03.mp3",
      "/wet_footstep-step-04.mp3",
      "/wet_footstep-step-05.mp3",
      "/wet_footstep-step-06.mp3",
    ],
  },
  draco: "/libs/draco/",
  basis: "/libs/basis/",
};
